<a href="https://colab.research.google.com/github/Shreyabansal3112/testing/blob/main/tf2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import `tensorflow`
import tensorflow as tf

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
result = tf.multiply(x1, x2)

# Print the result
print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [ ]:
# Import `tensorflow` 
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])



# Multiply
result = tf.multiply(x1, x2)

# Intialize the Session
sess = tf.compat.v1.Session()

# Print the result
print(sess.run(result))

# Close the session
sess.close()

[ 5 12 21 32]


In [ ]:
sess = tf.compat.v1.Session()

In [ ]:
# Import `tensorflow`
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
result = tf.multiply(x1, x2)

# Initialize Session and run `result`
with tf.compat.v1.Session() as ses:

  output = ses.run(result)
  print(output)

[ 5 12 21 32]


In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
X1=tf.Variable(initial_value=[0.,1.,0.,1.])
X2=tf.Variable(initial_value=[0.,0.,1.,1.])
Y_AND=tf.Variable(initial_value=[0.,0.,0.,1.])
Y_NOR=tf.Variable(initial_value=[1.,0.,0.,0.])
Y_OR=tf.Variable(initial_value=[0.,1.,1.,1.])
Y_XOR=tf.Variable(initial_value=[0.,1.,1.,0.])
Y_XNOR=tf.Variable(initial_value=[1.,0.,0.,1.])

In [ ]:
class Model(object):
 
   def __init__(self):
     # Initialize the weights to `2.0` and the bias to `2.0`
     # In practice, these should be initialized to random values
     # self.W1=tf.random.normal([1])
     self.W1 = tf.Variable(2.)
     self.W2= tf.Variable(2.)
     self.b=tf.Variable(2.)
   
   def __call__(self, x1,x2):
     self.K1=self.W1 * x1 + self.W2 * x2 + self.b
     self.Output = tf.keras.activations.sigmoid(self.K1)
     return(self.Output)
model=Model()

In [ ]:
def compute_cost(target_y, predicted_y):
    c=tf.keras.losses.BinaryCrossentropy()
    return(c(target_y,predicted_y))

In [ ]:
def None_to_Zero(v):
   if v==None:
      v=0
   return v

In [ ]:
def train(model, X1, X2, Y2, learning_rate):
     with tf.GradientTape() as t:
          current_loss = compute_cost(Y2,model(X1,X2))
     dW1,dW2,db=t.gradient(current_loss,[model.W1,model.W2,model.b])          
     dW1=None_to_Zero(dW1)
     db=None_to_Zero(db)
     dW2=None_to_Zero(dW2)
     model.W1.assign_sub(learning_rate * dW1)
     model.b.assign_sub(learning_rate * db)
     model.W2.assign_sub(learning_rate * dW2)

In [ ]:
# As we have very less Input data we need to increase the number of # epochs.
import numpy as np
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
   train(model, X1, X2,Y_AND, learning_rate)
   # train(model, X1, X2,Y_NOR, learning_rate)
   # train(model, X1, X2,Y_OR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

AttributeError: ignored

In [ ]:
W_AND={‘W1’:model.W1.numpy(),
       ’W2':model.W2.numpy(),
       ’b’:model.b.numpy()}
#W_NOR(calculated by keeping Y_NOR)={‘W1’:-8.65,’W2':-8.65,’b’:3.86}
#W_OR(calculated by keeping Y_OR)={‘W1’:8.69,’W2': 8.69,’b’: -3.88}